version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Stryker.CLI"
  schedule:
    interval: daily
  commit-message:
    prefix: 'deps: '
    include: "scope"
- package-ecosystem: nuget
  directory: "/integrationtest"
  schedule:
    interval: daily
  commit-message:
    prefix: 'deps: '
    include: "scope"
- package-ecosystem: nuget
  directory: "/integrationtest/TargetProjects/NetFramework"
  schedule:
    interval: daily
  commit-message:
    prefix: 'deps: '
    include: "scope"
- package-ecosystem: nuget
  directory: "/src/Stryker.Core/Stryker.Core/ToolHelpers"
  schedule:
    interval: daily
  commit-message:
    prefix: 'deps: '
    include: "scope"
