name: Stryker on Stryker

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      useLocalTool:
        description: 'Pack and use local Stryker CLI (instead of nuget tool)'
        type: boolean
        required: false
        default: false
  # When modifying the workflow, you can enable pull request trigger so it's easier to test changes, but we don't want to run this on every PR
  # pull_request:

concurrency:
  group: stryker-on-stryker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-stryker:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Stryker.Abstractions
            workingDirectory: src/Stryker.Abstractions
          - name: Stryker.CLI
            workingDirectory: src/Stryker.CLI/Stryker.CLI
          - name: Stryker.Core
            workingDirectory: src/Stryker.Core/Stryker.Core
          - name: Stryker.Configuration
            workingDirectory: src/Stryker.Configuration
          - name: Stryker.RegexMutators
            workingDirectory: src/Stryker.RegexMutators/Stryker.RegexMutators
          - name: Stryker.TestRunner
            workingDirectory: src/Stryker.TestRunner
          - name: Stryker.TestRunner.MicrosoftTestPlatform
            workingDirectory: src/Stryker.TestRunner.MicrosoftTestPlatform
          - name: Stryker.TestRunner.VsTest
            workingDirectory: src/Stryker.TestRunner.VsTest
          - name: Stryker.DataCollector
            workingDirectory: src/Stryker.DataCollector
          - name: Stryker.Solutions
            workingDirectory: src/Stryker.Solutions
          - name: Stryker.Utilities
            workingDirectory: src/Stryker.Utilities

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.x
            10.x

      - name: Run Stryker
        shell: pwsh
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY || '' }}
          USE_LOCAL_TOOL: ${{ inputs.useLocalTool }}
        run: ./stryker-on-stryker.ps1 -WorkingDirectory "${{ matrix.workingDirectory }}"

      - name: Upload Stryker logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-logs-${{ matrix.name }}
          path: ${{ matrix.workingDirectory }}/StrykerOutput/*/logs/
          if-no-files-found: ignore
